services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /src
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

volumes:
  mysql: