# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d33d551d8e5e2d879308cfeb30636ed44e2f79bd85b11fc2137fcd40a927d7f2e9994775eaf14f540cd78ea812e92b4f5fcb29c9f0e46bd3220ca2adfe9425d

test:
  secret_key_base: c250974379b154312ddc6dc77d9bffdd3e233302e3c5baea7de434c98454d75c0cf3f6568b4834526285263d0b4747c7625c5cf172150106ea01556972c9c9df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
